/**
 * Create or update a local login account, and make sure AUTH_SECRET exists in .env.
 *
 *   npx tsx scripts/create-user.ts <username> <password>
 *
 * - Password is scrypt-hashed (src/lib/auth.ts); plaintext is never stored.
 * - AUTH_SECRET (session-cookie HMAC key) is generated on first run and appended to .env,
 *   which is gitignored — the repo is public, so neither secret nor hash may be committed.
 * - Run db migrations first (users table): npm run db:generate && npm run db:migrate
 */
import { randomBytes } from 'node:crypto';
import { appendFileSync, existsSync, readFileSync } from 'node:fs';
import { eq } from 'drizzle-orm';
import { getDb } from '@/db/client';
import { users } from '@/db/schema';
import { hashPassword } from '@/lib/auth';

async function main() {
  const [username, password] = process.argv.slice(2);
  if (!username || !password) {
    console.error('usage: npx tsx scripts/create-user.ts <username> <password>');
    process.exit(1);
  }
  if (password.length < 8) {
    console.error('비밀번호는 8자 이상이어야 합니다.');
    process.exit(1);
  }

  // Ensure AUTH_SECRET in .env (created on first run).
  const envPath = '.env';
  const env = existsSync(envPath) ? readFileSync(envPath, 'utf8') : '';
  if (!/^AUTH_SECRET=/m.test(env)) {
    const secret = randomBytes(32).toString('hex');
    appendFileSync(
      envPath,
      `${env && !env.endsWith('\n') ? '\n' : ''}# Session-cookie HMAC key (generated by scripts/create-user.ts — keep out of git)\nAUTH_SECRET=${secret}\n`,
    );
    console.log('AUTH_SECRET 생성 → .env (web 재시작 필요)');
  }

  const db = getDb();
  const passwordHash = hashPassword(password);
  const existing = (await db.select().from(users).where(eq(users.username, username)).limit(1))[0];
  if (existing) {
    await db.update(users).set({ passwordHash }).where(eq(users.id, existing.id));
    console.log(`기존 계정 비밀번호 갱신: ${username}`);
  } else {
    await db.insert(users).values({ username, passwordHash });
    console.log(`계정 생성: ${username}`);
  }
}

main()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
